repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: end-of-file-fixer
      exclude: '^LICENSE$'
    - id: check-yaml
    - id: check-added-large-files

- repo: meta
  hooks:
    - id: check-useless-excludes

- repo: https://codeberg.org/vifon/pre-commit-hooks
  rev: 779f29ebd525d11923aa3578b3a94a13bbef1249
  hooks:
    - id: shellcheck
    - id: elisp-check-parens
    - id: elisp-checkdoc
    - id: elisp-package-lint
      args: [--main-file, zettel2.el]
    - id: no-elc
    - id: no-tabs

- repo: https://github.com/vifon/elisp-lint
  rev: b5fd5cb973571cde3d6ee69a5bb9cdaf74648664
  hooks:
    - id: elisp-lint
      args: [--main-file, zettel2.el]
    - id: elisp-lint-cleanup
