repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: end-of-file-fixer
      exclude: '^LICENSE$'
    - id: check-yaml
    - id: check-added-large-files

- repo: meta
  hooks:
    - id: check-useless-excludes

- repo: https://codeberg.org/vifon/pre-commit-hooks
  rev: e29e31052769a9495e9b182b6103a8baf2dc5544
  hooks:
    - id: shellcheck
    - id: elisp-check-parens
    # # TODO: Fix and enable this hook.
    # - id: elisp-checkdoc
    - id: elisp-package-lint
      args: [--main-file, zettel2.el]
    - id: no-elc
    - id: no-tabs
